-- CRIMSON RONIN // RED-BLACK LIQUID GLASS
-- Hyprland 0.56 Lua config. DP-1 is intentionally capped at 144 Hz.
hl.config({ autogenerated = false })

hl.monitor({ output = "DP-1", mode = "1920x1080@144", position = "0x0", scale = 1 })

local terminal = "ghostty"
local browser = "helium"
local fileManager = "thunar"

hl.on("hyprland.start", function()
    hl.exec_cmd("caelestia shell -d")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("TERMINAL", "ghostty")
hl.env("BROWSER", "helium")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.config({
    general = {
        gaps_in = 8, gaps_out = 12, border_size = 1,
        resize_on_border = true, allow_tearing = false, layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(24242Bdd)", "rgba(720B12ee)", "rgba(E21A28ff)", "rgba(24242Bdd)" }, angle = 32 },
            inactive_border = "rgba(24242B66)",
        },
    },
    decoration = {
        rounding = 16, rounding_power = 2.8,
        active_opacity = 0.95, inactive_opacity = 0.89, fullscreen_opacity = 1.0,
        dim_inactive = true, dim_strength = 0.06,
        shadow = {
            enabled = true, range = 20, render_power = 3,
            color = "rgba(000000c0)", color_inactive = "rgba(00000078)",
            offset = { 0, 6 }, scale = 0.98,
        },
        blur = {
            enabled = true, size = 10, passes = 2,
            ignore_opacity = true, new_optimizations = true,
            noise = 0.008, contrast = 1.10, brightness = 0.74,
            vibrancy = 0.08, vibrancy_darkness = 0.22,
            popups = true, popups_ignorealpha = 0.16,
        },
    },
    animations = { enabled = true },
    dwindle = { preserve_split = true },
    input = {
        kb_layout = "us", follow_mouse = 1, sensitivity = -1.0,
        touchpad = { natural_scroll = false },
    },
    misc = {
        force_default_wallpaper = 0, disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Katana motion: fast acceleration, decisive stop, no bounce.
hl.curve("roninOut", { type = "bezier", points = { { 0.16, 1.0 }, { 0.30, 1.0 } } })
hl.curve("roninIn", { type = "bezier", points = { { 0.55, 0.0 }, { 1.0, 0.45 } } })
hl.curve("roninFlow", { type = "bezier", points = { { 0.22, 0.72 }, { 0.18, 1.0 } } })
hl.animation({ leaf = "global", enabled = true, speed = 8, bezier = "roninOut" })
hl.animation({ leaf = "border", enabled = true, speed = 4.8, bezier = "roninOut" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.8, bezier = "roninOut" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.2, bezier = "roninOut", style = "popin 96%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.3, bezier = "roninIn", style = "popin 97%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4.0, bezier = "roninFlow" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.2, bezier = "roninOut" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2.1, bezier = "roninIn" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.8, bezier = "roninOut" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 3.5, bezier = "roninOut", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 2.2, bezier = "roninIn", style = "fade" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4.4, bezier = "roninFlow", style = "slidefade 12%" })
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

local function bind(key, dispatcher, opts) hl.bind(key, dispatcher, opts) end

-- Omarchy workflow: each requested chord exists exactly once.
bind("SUPER + RETURN", hl.dsp.exec_cmd(terminal))
bind("SUPER + SHIFT + RETURN", hl.dsp.exec_cmd(browser))
bind("SUPER + Q", hl.dsp.window.close())
bind("SUPER + W", hl.dsp.window.close())
bind("SUPER + SPACE", hl.dsp.global("caelestia:launcher"))
bind("SUPER + ESCAPE", hl.dsp.global("caelestia:session"))
bind("SUPER + E", hl.dsp.exec_cmd(fileManager))
bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
bind("SUPER + T", hl.dsp.window.float({ action = "toggle" }))
bind("SUPER + P", hl.dsp.window.pseudo({ action = "toggle" }))
bind("SUPER + J", hl.dsp.layout("togglesplit"))

bind("SUPER + LEFT", hl.dsp.focus({ direction = "l" }))
bind("SUPER + RIGHT", hl.dsp.focus({ direction = "r" }))
bind("SUPER + UP", hl.dsp.focus({ direction = "u" }))
bind("SUPER + DOWN", hl.dsp.focus({ direction = "d" }))
bind("SUPER + SHIFT + LEFT", hl.dsp.window.swap({ direction = "l" }))
bind("SUPER + SHIFT + RIGHT", hl.dsp.window.swap({ direction = "r" }))
bind("SUPER + SHIFT + UP", hl.dsp.window.swap({ direction = "u" }))
bind("SUPER + SHIFT + DOWN", hl.dsp.window.swap({ direction = "d" }))
bind("ALT + TAB", hl.dsp.window.cycle_next())
bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }))

for i = 1, 10 do
    local key = i == 10 and "0" or tostring(i)
    bind("SUPER + " .. key, hl.dsp.focus({ workspace = i }))
    bind("SUPER + SHIFT + " .. key, function()
        hl.dispatch(hl.dsp.window.move({ workspace = i }))
        hl.dispatch(hl.dsp.focus({ workspace = i }))
    end)
    bind("SUPER + SHIFT + ALT + " .. key, hl.dsp.window.move({ workspace = i }))
end

bind("SUPER + TAB", hl.dsp.focus({ workspace = "e+1" }))
bind("SUPER + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }))
bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
bind("SUPER + S", hl.dsp.workspace.toggle_special("scratch"))
bind("SUPER + ALT + S", hl.dsp.window.move({ workspace = "special:scratch" }))
bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

bind("SUPER + CTRL + L", hl.dsp.exec_cmd("hyprlock"))
bind("SUPER + CTRL + V", hl.dsp.global("caelestia:clipboard"))
bind("SUPER + CTRL + E", hl.dsp.global("caelestia:emoji"))
bind("SUPER + K", hl.dsp.global("caelestia:keybinds"))
bind("SUPER + CTRL + SPACE", hl.dsp.global("caelestia:wallpaper"))
bind("Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))
bind("SUPER + SHIFT + S", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | swappy -f -]]))

bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })
bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { repeating = true })
bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { repeating = true })

hl.window_rule({ name = "suppress-maximize-events", match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({
    name = "fix-xwayland-drags",
    match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false },
    no_focus = true,
})
hl.window_rule({
    name = "opaque-fullscreen", match = { fullscreen = true },
    opacity = "1.0 override 1.0 override 1.0 override", rounding = 0, border_size = 0,
})
hl.layer_rule({ name = "caelestia-glass", match = { namespace = "caelestia-drawers" }, blur = true, blur_popups = true, ignore_alpha = 0.72 })
